name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: u415105283_codemitro
          MYSQL_USER: u415105283_codemitro
          MYSQL_PASSWORD: "eh*kVCUZ7WD&WfN"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, zip, xml, gd, pdo_mysql

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Update .env for GitHub Actions
      run: |
        sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_DATABASE=laravel/DB_DATABASE=u415105283_codemitro/' .env
        sed -i 's/DB_USERNAME=root/DB_USERNAME=u415105283_codemitro/' .env
        sed -i 's/DB_PASSWORD=/DB_PASSWORD="eh*kVCUZ7WD&WfN"/' .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

    - name: Debugging Step
      run: |
        sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=mysql/' .env
        echo "Printing environment variables:"
        echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
        echo "REMOTE_HOST: ${{ secrets.REMOTE_HOST }}"
        echo "REMOTE_USER: ${{ secrets.REMOTE_USER }}"
        echo "Current directory:"
        pwd
        echo "Listing files:"
        ls -la

    - name: Deploy to Server
      if: github.ref == 'refs/heads/master'
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: "65002"
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "public/"
        TARGET: "/home/u415105283/"  # Replace with your actual target path
