name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, zip, xml, gd, pdo_mysql

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Uncomment if you need to copy .env.example to .env
    # - name: Copy .env.example to .env
    #   run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

    # Debugging Step: Print environment variables and current directory
    - name: Debugging Step
      run: |
        echo "Printing environment variables:"
        echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
        echo "REMOTE_HOST: ${{ secrets.REMOTE_HOST }}"
        echo "REMOTE_USER: ${{ secrets.REMOTE_USER }}"
        echo "Current directory:"
        pwd
        echo "Listing files:"
        ls -la

    - name: Deploy to Server
      if: github.ref == 'refs/heads/master'
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: "65002"
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "public/"
        TARGET: "/home/u415105283/"  # Replace with your actual target path
